# Generated by Django 5.2.1 on 2026-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(default='general', max_length=64)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('customer_support', 'Customer Support'), ('inventory_manager', 'Inventory Manager'), ('payment_reviewer', 'Payment Reviewer'), ('content_manager', 'Content Manager'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.permission'),
        ),
    ]
