# Generated by Django 5.2.1 on 2026-08-17 14:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=128, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name_ar'),
            },
        ),
        migrations.CreateModel(
            name='StoreShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Global free-shipping threshold (overrides per-governorate when set).', max_digits=12, null=True)),
                ('default_estimated_delivery_days', models.PositiveIntegerField(default=3)),
                ('inventory_reservation_policy', models.CharField(choices=[('none', 'No reservation'), ('hold', 'Reserve until confirmation'), ('deduct', 'Deduct immediately')], default='hold', max_length=20)),
                ('reservation_hours', models.PositiveIntegerField(default=48, help_text='How long a held reservation lasts.')),
            ],
            options={
                'verbose_name': 'Store shipping settings',
                'verbose_name_plural': 'Store shipping settings',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal at or above this value ships free for this governorate.', max_digits=12, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('governorate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rate', to='shipping.governorate')),
            ],
            options={
                'ordering': ('governorate__name_ar',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=128)),
                ('name_en', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipping.governorate')),
            ],
            options={
                'ordering': ('name_ar',),
                'unique_together': {('governorate', 'name_ar')},
            },
        ),
    ]
