# Generated by Django 5.2.1 on 2026-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('wa_link', models.CharField(blank=True, max_length=2000)),
                ('related_order', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='رقم واتساب بصيغة محلية مثل 01037839725', max_length=15)),
                ('welcome_message', models.TextField(default='أهلًا بك في YK9 👋')),
                ('templates', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'WhatsApp settings',
                'verbose_name_plural': 'WhatsApp settings',
            },
        ),
    ]
