# Generated by Django 5.2.1 on 2026-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
